
CREATE TABLE worker (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000),
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL ENUM('Trainee', 'Junior', 'Middle', 'Senior') NOT NULL,
    SALARY INT CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000)
);

CREATE TABLE project (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INT,
    START_DATE DATE,
    FINISH_DATE DATE
);

CREATE TABLE project_worker (
    PROJECT_ID INT REFERENCES project(id),
    WORKER_ID INT REFERENCES worker,
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);

